---
apiVersion: v1
kind: Service
metadata:
  name: asuggs-test-flask-service
  label:
    username: asuggs
    env: test
spec:
  type: ClusterIP
  selector:
    matchLabel:
      app: asuggs-test-flask
  template:
    metadata:
      labels:
        username: asuggs
        env: test
  ports:
  - name: helloflask
    port: 5000
    targetPort: 5000