---
apiVersion: v1
kind: Service
metadata:
  username: asuggs
  env: test
spec:
  type: ClusterIP
  selector:
    matchLabels:
      app: asuggs-test-redis
  template:
    metadata:
      labels:
        username: asuggs
        env: test
  ports:
  - name: helloflask
    port: 6379
    targetPort: 6379